insert into t_cliente values ('No 200-13-04-013',
								'FORMULACIÓN DEL PLAN MAESTRO PARA EL SISTEMA DE ACUEDUCTO DEL DISTRITO DE BUENAVENTURA-VALLE DEL CAUCA Y ELABORACIÓN DE ESTUDIOS Y DISEÑOS DE LAS OBRAS PRIORITARIAS, DE CONFORMIDAD CON EL DETALLE Y DESCRIPCIÓN DEL OBJETO, CARACTERÍSTICAS Y CONDICIONES PRESENTADAS EN LOS ANEXOS CONTENIDOS EN EL PLIEGO',
								'AMPLIACIÓN DE LA PLANTA DE TRATAMIENTO DE AGUA POTABLE DE VENECIA EN EL DISTRITO DE BUENAVENTURA, DEPARTAMENTO DE VALLE DEL CAUCA', 
								45278487846.0789);
select * from t_cliente